@startuml Теплый дом Context 
!include <C4/C4_Context>

title Диаграмма контекста — Система управления датчиками

Person(engineer, "Инженер", "Регистрирует датчики в системе на выезде")
Person(client, "Пользователь", "Владеет зарегистрированным в системе датчиком")

System(smarthome, "Система управление отоплением", "Управление регистрацией датчиков отопление, управляет отопление и собирает текущие показания")

System_Ext(sensor, "Датчик", "Устройство, зарегистрованное в системе", $sprite="robot")

' Связи
Rel(client, smarthome, "Включает/отключает отопленени и смотрит показания температуры", "HTTPS")
Rel(engineer, smarthome, "Регистрирует новые датчики в системе", "HTTPS")
Rel(engineer, sensor, "Физически устанавливает датчик")
Rel(smarthome, sensor, "Запрашивает актуальные показания и управляет датчиками", "REST API")

SHOW_LEGEND()
@enduml