@startuml Теплый дом Context 
!include <C4/C4_Context>

title Теплый Дом as-is - С4/Context

Person(engineer, "Инженер", "Устанавливает датчики")
Person(client, "Пользователь", "Управляет датчиками, зарегистрированными в системе")

System(smarthome, "Система управление отоплением", "Управление регистрацией датчиков отопление, управляет отопление и собирает текущие показания")

System_Ext(sensor, "Датчик", "Устройство, зарегистрованное в системе", $sprite="robot")

Rel(client, smarthome, "Включает/отключает отопление и смотрит показания температуры", "HTTPS")
Rel(sensor, smarthome, "Регистрируется в системе при включении", "HTTPS")
Rel(engineer, sensor, "Физически устанавливает датчик")
Rel(smarthome, sensor, "Запрашивает актуальные показания и управляет", "REST API")

SHOW_LEGEND()
@enduml