// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: remote_device_control_service_spec.proto

package remotecontrol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RemoteControlCommandService_Send_FullMethodName                 = "/remote_control_command.v1.RemoteControlCommandService/Send"
	RemoteControlCommandService_Cancel_FullMethodName               = "/remote_control_command.v1.RemoteControlCommandService/Cancel"
	RemoteControlCommandService_GetResult_FullMethodName            = "/remote_control_command.v1.RemoteControlCommandService/GetResult"
	RemoteControlCommandService_GetResultsBySensorId_FullMethodName = "/remote_control_command.v1.RemoteControlCommandService/GetResultsBySensorId"
)

// RemoteControlCommandServiceClient is the client API for RemoteControlCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RemoteControlCommandServiceClient interface {
	Send(ctx context.Context, in *SendCommandRequest, opts ...grpc.CallOption) (*CommandResult, error)
	Cancel(ctx context.Context, in *CommandId, opts ...grpc.CallOption) (*CommandResult, error)
	GetResult(ctx context.Context, in *CommandId, opts ...grpc.CallOption) (*CommandResult, error)
	GetResultsBySensorId(ctx context.Context, in *SensorId, opts ...grpc.CallOption) (*CommandResults, error)
}

type remoteControlCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRemoteControlCommandServiceClient(cc grpc.ClientConnInterface) RemoteControlCommandServiceClient {
	return &remoteControlCommandServiceClient{cc}
}

func (c *remoteControlCommandServiceClient) Send(ctx context.Context, in *SendCommandRequest, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, RemoteControlCommandService_Send_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteControlCommandServiceClient) Cancel(ctx context.Context, in *CommandId, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, RemoteControlCommandService_Cancel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteControlCommandServiceClient) GetResult(ctx context.Context, in *CommandId, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, RemoteControlCommandService_GetResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteControlCommandServiceClient) GetResultsBySensorId(ctx context.Context, in *SensorId, opts ...grpc.CallOption) (*CommandResults, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResults)
	err := c.cc.Invoke(ctx, RemoteControlCommandService_GetResultsBySensorId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemoteControlCommandServiceServer is the server API for RemoteControlCommandService service.
// All implementations must embed UnimplementedRemoteControlCommandServiceServer
// for forward compatibility.
type RemoteControlCommandServiceServer interface {
	Send(context.Context, *SendCommandRequest) (*CommandResult, error)
	Cancel(context.Context, *CommandId) (*CommandResult, error)
	GetResult(context.Context, *CommandId) (*CommandResult, error)
	GetResultsBySensorId(context.Context, *SensorId) (*CommandResults, error)
	mustEmbedUnimplementedRemoteControlCommandServiceServer()
}

// UnimplementedRemoteControlCommandServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRemoteControlCommandServiceServer struct{}

func (UnimplementedRemoteControlCommandServiceServer) Send(context.Context, *SendCommandRequest) (*CommandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedRemoteControlCommandServiceServer) Cancel(context.Context, *CommandId) (*CommandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Cancel not implemented")
}
func (UnimplementedRemoteControlCommandServiceServer) GetResult(context.Context, *CommandId) (*CommandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method GetResult not implemented")
}
func (UnimplementedRemoteControlCommandServiceServer) GetResultsBySensorId(context.Context, *SensorId) (*CommandResults, error) {
	return nil, status.Error(codes.Unimplemented, "method GetResultsBySensorId not implemented")
}
func (UnimplementedRemoteControlCommandServiceServer) mustEmbedUnimplementedRemoteControlCommandServiceServer() {
}
func (UnimplementedRemoteControlCommandServiceServer) testEmbeddedByValue() {}

// UnsafeRemoteControlCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RemoteControlCommandServiceServer will
// result in compilation errors.
type UnsafeRemoteControlCommandServiceServer interface {
	mustEmbedUnimplementedRemoteControlCommandServiceServer()
}

func RegisterRemoteControlCommandServiceServer(s grpc.ServiceRegistrar, srv RemoteControlCommandServiceServer) {
	// If the following call panics, it indicates UnimplementedRemoteControlCommandServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RemoteControlCommandService_ServiceDesc, srv)
}

func _RemoteControlCommandService_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteControlCommandServiceServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemoteControlCommandService_Send_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteControlCommandServiceServer).Send(ctx, req.(*SendCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteControlCommandService_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteControlCommandServiceServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemoteControlCommandService_Cancel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteControlCommandServiceServer).Cancel(ctx, req.(*CommandId))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteControlCommandService_GetResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteControlCommandServiceServer).GetResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemoteControlCommandService_GetResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteControlCommandServiceServer).GetResult(ctx, req.(*CommandId))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteControlCommandService_GetResultsBySensorId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SensorId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteControlCommandServiceServer).GetResultsBySensorId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemoteControlCommandService_GetResultsBySensorId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteControlCommandServiceServer).GetResultsBySensorId(ctx, req.(*SensorId))
	}
	return interceptor(ctx, in, info, handler)
}

// RemoteControlCommandService_ServiceDesc is the grpc.ServiceDesc for RemoteControlCommandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RemoteControlCommandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "remote_control_command.v1.RemoteControlCommandService",
	HandlerType: (*RemoteControlCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _RemoteControlCommandService_Send_Handler,
		},
		{
			MethodName: "Cancel",
			Handler:    _RemoteControlCommandService_Cancel_Handler,
		},
		{
			MethodName: "GetResult",
			Handler:    _RemoteControlCommandService_GetResult_Handler,
		},
		{
			MethodName: "GetResultsBySensorId",
			Handler:    _RemoteControlCommandService_GetResultsBySensorId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "remote_device_control_service_spec.proto",
}
