// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: remote_device_control_service_spec.proto

package remotecontrol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandStatus int32

const (
	CommandStatus_COMMAND_STATUS_UNSPECIFIED CommandStatus = 0
	CommandStatus_COMMAND_STATUS_PENDING     CommandStatus = 1
	CommandStatus_COMMAND_STATUS_PROCESSING  CommandStatus = 2
	CommandStatus_COMMAND_STATUS_DONE        CommandStatus = 3
	CommandStatus_COMMAND_STATUS_CANCELLED   CommandStatus = 4
	CommandStatus_COMMAND_STATUS_FAILED      CommandStatus = 5
)

// Enum value maps for CommandStatus.
var (
	CommandStatus_name = map[int32]string{
		0: "COMMAND_STATUS_UNSPECIFIED",
		1: "COMMAND_STATUS_PENDING",
		2: "COMMAND_STATUS_PROCESSING",
		3: "COMMAND_STATUS_DONE",
		4: "COMMAND_STATUS_CANCELLED",
		5: "COMMAND_STATUS_FAILED",
	}
	CommandStatus_value = map[string]int32{
		"COMMAND_STATUS_UNSPECIFIED": 0,
		"COMMAND_STATUS_PENDING":     1,
		"COMMAND_STATUS_PROCESSING":  2,
		"COMMAND_STATUS_DONE":        3,
		"COMMAND_STATUS_CANCELLED":   4,
		"COMMAND_STATUS_FAILED":      5,
	}
)

func (x CommandStatus) Enum() *CommandStatus {
	p := new(CommandStatus)
	*p = x
	return p
}

func (x CommandStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_remote_device_control_service_spec_proto_enumTypes[0].Descriptor()
}

func (CommandStatus) Type() protoreflect.EnumType {
	return &file_remote_device_control_service_spec_proto_enumTypes[0]
}

func (x CommandStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandStatus.Descriptor instead.
func (CommandStatus) EnumDescriptor() ([]byte, []int) {
	return file_remote_device_control_service_spec_proto_rawDescGZIP(), []int{0}
}

type SendCommandRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Code           string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	SensorId       uint64                 `protobuf:"varint,3,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	InputPayload   *structpb.Struct       `protobuf:"bytes,4,opt,name=input_payload,json=inputPayload,proto3" json:"input_payload,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendCommandRequest) Reset() {
	*x = SendCommandRequest{}
	mi := &file_remote_device_control_service_spec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCommandRequest) ProtoMessage() {}

func (x *SendCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_device_control_service_spec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCommandRequest.ProtoReflect.Descriptor instead.
func (*SendCommandRequest) Descriptor() ([]byte, []int) {
	return file_remote_device_control_service_spec_proto_rawDescGZIP(), []int{0}
}

func (x *SendCommandRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SendCommandRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *SendCommandRequest) GetSensorId() uint64 {
	if x != nil {
		return x.SensorId
	}
	return 0
}

func (x *SendCommandRequest) GetInputPayload() *structpb.Struct {
	if x != nil {
		return x.InputPayload
	}
	return nil
}

type CommandId struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uuid
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandId) Reset() {
	*x = CommandId{}
	mi := &file_remote_device_control_service_spec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandId) ProtoMessage() {}

func (x *CommandId) ProtoReflect() protoreflect.Message {
	mi := &file_remote_device_control_service_spec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandId.ProtoReflect.Descriptor instead.
func (*CommandId) Descriptor() ([]byte, []int) {
	return file_remote_device_control_service_spec_proto_rawDescGZIP(), []int{1}
}

func (x *CommandId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SensorId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorId) Reset() {
	*x = SensorId{}
	mi := &file_remote_device_control_service_spec_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorId) ProtoMessage() {}

func (x *SensorId) ProtoReflect() protoreflect.Message {
	mi := &file_remote_device_control_service_spec_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorId.ProtoReflect.Descriptor instead.
func (*SensorId) Descriptor() ([]byte, []int) {
	return file_remote_device_control_service_spec_proto_rawDescGZIP(), []int{2}
}

func (x *SensorId) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        CommandStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=remote_control_command.v1.CommandStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	InputPayload  *structpb.Struct       `protobuf:"bytes,5,opt,name=input_payload,json=inputPayload,proto3" json:"input_payload,omitempty"`
	ResultData    *structpb.Struct       `protobuf:"bytes,6,opt,name=result_data,json=resultData,proto3" json:"result_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_remote_device_control_service_spec_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_remote_device_control_service_spec_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_remote_device_control_service_spec_proto_rawDescGZIP(), []int{3}
}

func (x *CommandResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CommandResult) GetStatus() CommandStatus {
	if x != nil {
		return x.Status
	}
	return CommandStatus_COMMAND_STATUS_UNSPECIFIED
}

func (x *CommandResult) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CommandResult) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *CommandResult) GetInputPayload() *structpb.Struct {
	if x != nil {
		return x.InputPayload
	}
	return nil
}

func (x *CommandResult) GetResultData() *structpb.Struct {
	if x != nil {
		return x.ResultData
	}
	return nil
}

type CommandResults struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*CommandResult       `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResults) Reset() {
	*x = CommandResults{}
	mi := &file_remote_device_control_service_spec_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResults) ProtoMessage() {}

func (x *CommandResults) ProtoReflect() protoreflect.Message {
	mi := &file_remote_device_control_service_spec_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResults.ProtoReflect.Descriptor instead.
func (*CommandResults) Descriptor() ([]byte, []int) {
	return file_remote_device_control_service_spec_proto_rawDescGZIP(), []int{4}
}

func (x *CommandResults) GetResults() []*CommandResult {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_remote_device_control_service_spec_proto protoreflect.FileDescriptor

const file_remote_device_control_service_spec_proto_rawDesc = "" +
	"\n" +
	"(remote_device_control_service_spec.proto\x12\x19remote_control_command.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xac\x01\n" +
	"\x12SendCommandRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12\x1b\n" +
	"\tsensor_id\x18\x03 \x01(\x04R\bsensorId\x12<\n" +
	"\rinput_payload\x18\x04 \x01(\v2\x17.google.protobuf.StructR\finputPayload\"\x1b\n" +
	"\tCommandId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1a\n" +
	"\bSensorId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\xd1\x02\n" +
	"\rCommandResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12@\n" +
	"\x06status\x18\x02 \x01(\x0e2(.remote_control_command.v1.CommandStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12;\n" +
	"\vfinished_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x12<\n" +
	"\rinput_payload\x18\x05 \x01(\v2\x17.google.protobuf.StructR\finputPayload\x128\n" +
	"\vresult_data\x18\x06 \x01(\v2\x17.google.protobuf.StructR\n" +
	"resultData\"T\n" +
	"\x0eCommandResults\x12B\n" +
	"\aresults\x18\x01 \x03(\v2(.remote_control_command.v1.CommandResultR\aresults*\xbc\x01\n" +
	"\rCommandStatus\x12\x1e\n" +
	"\x1aCOMMAND_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16COMMAND_STATUS_PENDING\x10\x01\x12\x1d\n" +
	"\x19COMMAND_STATUS_PROCESSING\x10\x02\x12\x17\n" +
	"\x13COMMAND_STATUS_DONE\x10\x03\x12\x1c\n" +
	"\x18COMMAND_STATUS_CANCELLED\x10\x04\x12\x19\n" +
	"\x15COMMAND_STATUS_FAILED\x10\x052\x9d\x03\n" +
	"\x1bRemoteControlCommandService\x12_\n" +
	"\x04Send\x12-.remote_control_command.v1.SendCommandRequest\x1a(.remote_control_command.v1.CommandResult\x12X\n" +
	"\x06Cancel\x12$.remote_control_command.v1.CommandId\x1a(.remote_control_command.v1.CommandResult\x12[\n" +
	"\tGetResult\x12$.remote_control_command.v1.CommandId\x1a(.remote_control_command.v1.CommandResult\x12f\n" +
	"\x14GetResultsBySensorId\x12#.remote_control_command.v1.SensorId\x1a).remote_control_command.v1.CommandResultsB-Z+smarthome/proto/remotecontrol;remotecontrolb\x06proto3"

var (
	file_remote_device_control_service_spec_proto_rawDescOnce sync.Once
	file_remote_device_control_service_spec_proto_rawDescData []byte
)

func file_remote_device_control_service_spec_proto_rawDescGZIP() []byte {
	file_remote_device_control_service_spec_proto_rawDescOnce.Do(func() {
		file_remote_device_control_service_spec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_remote_device_control_service_spec_proto_rawDesc), len(file_remote_device_control_service_spec_proto_rawDesc)))
	})
	return file_remote_device_control_service_spec_proto_rawDescData
}

var file_remote_device_control_service_spec_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_remote_device_control_service_spec_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_remote_device_control_service_spec_proto_goTypes = []any{
	(CommandStatus)(0),            // 0: remote_control_command.v1.CommandStatus
	(*SendCommandRequest)(nil),    // 1: remote_control_command.v1.SendCommandRequest
	(*CommandId)(nil),             // 2: remote_control_command.v1.CommandId
	(*SensorId)(nil),              // 3: remote_control_command.v1.SensorId
	(*CommandResult)(nil),         // 4: remote_control_command.v1.CommandResult
	(*CommandResults)(nil),        // 5: remote_control_command.v1.CommandResults
	(*structpb.Struct)(nil),       // 6: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_remote_device_control_service_spec_proto_depIdxs = []int32{
	6,  // 0: remote_control_command.v1.SendCommandRequest.input_payload:type_name -> google.protobuf.Struct
	0,  // 1: remote_control_command.v1.CommandResult.status:type_name -> remote_control_command.v1.CommandStatus
	7,  // 2: remote_control_command.v1.CommandResult.created_at:type_name -> google.protobuf.Timestamp
	7,  // 3: remote_control_command.v1.CommandResult.finished_at:type_name -> google.protobuf.Timestamp
	6,  // 4: remote_control_command.v1.CommandResult.input_payload:type_name -> google.protobuf.Struct
	6,  // 5: remote_control_command.v1.CommandResult.result_data:type_name -> google.protobuf.Struct
	4,  // 6: remote_control_command.v1.CommandResults.results:type_name -> remote_control_command.v1.CommandResult
	1,  // 7: remote_control_command.v1.RemoteControlCommandService.Send:input_type -> remote_control_command.v1.SendCommandRequest
	2,  // 8: remote_control_command.v1.RemoteControlCommandService.Cancel:input_type -> remote_control_command.v1.CommandId
	2,  // 9: remote_control_command.v1.RemoteControlCommandService.GetResult:input_type -> remote_control_command.v1.CommandId
	3,  // 10: remote_control_command.v1.RemoteControlCommandService.GetResultsBySensorId:input_type -> remote_control_command.v1.SensorId
	4,  // 11: remote_control_command.v1.RemoteControlCommandService.Send:output_type -> remote_control_command.v1.CommandResult
	4,  // 12: remote_control_command.v1.RemoteControlCommandService.Cancel:output_type -> remote_control_command.v1.CommandResult
	4,  // 13: remote_control_command.v1.RemoteControlCommandService.GetResult:output_type -> remote_control_command.v1.CommandResult
	5,  // 14: remote_control_command.v1.RemoteControlCommandService.GetResultsBySensorId:output_type -> remote_control_command.v1.CommandResults
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_remote_device_control_service_spec_proto_init() }
func file_remote_device_control_service_spec_proto_init() {
	if File_remote_device_control_service_spec_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_remote_device_control_service_spec_proto_rawDesc), len(file_remote_device_control_service_spec_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_remote_device_control_service_spec_proto_goTypes,
		DependencyIndexes: file_remote_device_control_service_spec_proto_depIdxs,
		EnumInfos:         file_remote_device_control_service_spec_proto_enumTypes,
		MessageInfos:      file_remote_device_control_service_spec_proto_msgTypes,
	}.Build()
	File_remote_device_control_service_spec_proto = out.File
	file_remote_device_control_service_spec_proto_goTypes = nil
	file_remote_device_control_service_spec_proto_depIdxs = nil
}
